config/routes.rb
TrackieApp::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }

  root 'dashboard#index'

     match 'versions/:id' => "versions#revert", as: :revert_version, via: [:get, :post]
resources :dashboard
resources :expense_types
  resources :income_types
    resources :incomes
      resources :expenses

    

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  helper_method :balance
  helper_method :see_if_users_accepted_invitation

  def index
  end
  
  def balance
    Income.where("created_at BETWEEN ? AND ?", DateTime.now.beginning_of_month, DateTime.now).sum(:amount) -
    Expense.where("created_at BETWEEN ? AND ?", DateTime.now.beginning_of_month, DateTime.now).sum(:amount)
  end

  def see_if_users_accepted_invitation
    user = User.find(2)
    user.invitation_accepted?
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="page-header">
    <h1> Welcome to Trackie, <%= link_to "#{current_user.username}", edit_user_registration_path %>!</span></h1>
</div></br></br>

<h2>
<p><%= "What do you want to do today?" %></br></br>
  <% if IncomeType.nil? %>
    You have to add an income type first. Click <%= link_to "here", new_income_type_path %> to add a new one. </br></br>
  <% else %>
    <% if Income.last.present? %>
      Your last added income is: <span style="color:green"> 
        <%= "#{Income.last.try(:amount)} RON " %> </span> in 
        <%= "#{Income.last.try(:income_type).try(:name)}" %>
        <%= link_to "add new", new_income_path %> Income </br></br>
    <% else %>
      You don't have any incomes added yet. You can
      <%= link_to "add new", new_income_path %> Incomes now. </br></br>
    <% end %>
  <% end %>

  <% if ExpenseType.nil? %>
    You have to add an expense type first. Click <%= link_to "here", new_expense_type_path %> to add a new one. </br></br>
  <% else %>
    <% if Expense.last.present? %>
      Your last added expense is: <span style="color:red"> <%= "#{Expense.last.try(:amount)} RON " %></span> in 
      <%= "#{Expense.last.try(:expense_type).try(:name)}" %> -
      <%= link_to "add new", new_expense_path %> Expese </br></br>
    <% else %>
      You don't have any expenses added yet. You can
      <%= link_to "add new", new_expense_path %> Expenses now. </br></br>
    <% end %>
  <% end %>

    Your balance for this month is: <span style="color:green"> 
      <%= "#{balance}" %> RON.</span>
      <%= link_to "See", "#" %> detailed information about your month so far.</span></p>
      <%= "#{see_if_users_accepted_invitation}" %>
</h2>