config/routes.rb
TrackieApp::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }

  root 'dashboard#index'

     match 'versions/:id' => "versions#revert", as: :revert_version, via: [:get, :post]
resources :dashboard
resources :expense_types
  resources :income_types
    resources :incomes
      resources :expenses

    

end

app/controllers/income_types_controller.rb
class IncomeTypesController < ApplicationController
  respond_to :html, :js
  
  helper_method :nil_parent_income_type
  helper_method :income_type_params
  
  def new
    @income_type = IncomeType.new
  end
  
  def create
    @income_type = IncomeType.new(income_type_params)
    @income_type.user_id = current_user.id
    if @income_type.save
      flash[:notice] = "Income Type #{income_type.name} was successfully created!"
      redirect_to action: 'index' 
    else
      render 'new'
    end
  end

  def index
    @income_types = IncomeType.page(params[:page]).per(5).order('created_at DESC')#paginate :per_page => 5, :page => params[:page]
  end

  def edit
    income_type
  end

  def update
    income_type
    if @income_type.update(income_type_params)
      flash[:notice] = "Income Type #{income_type.name} updated! #{undo_link} this!"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    income_type
    income_type.destroy
    respond_to do |format|
      format.html { redirect_to(income_types_path) }
      format.js   { render :nothing => true }
    #flash[:notice] = "You have successfully deleted #{income_type.name} income type. Press #{undo_link} to add it back!"
    #redirect_to income_types_path
    end
  end

  def income_type_params
    params.require(:income_type).permit(:user_id, :name, :parent_income_type_id)
  end

  def income_type
     @income_type ||= IncomeType.find(params[:id])
  end

private

  def nil_parent_income_type
      @unassigned_parrent = IncomeType.where(parent_income_type_id: nil).includes(:child_income_types)
  end
  
  def undo_link
    undo_link = view_context.link_to("undo", revert_version_path(@income_type.versions.scoped.last, :method => :post))
  end

end

app/helpers/income_types_helper.rb
module IncomeTypesHelper
end

app/views/income_types/_form.html.erb
<%= simple_form_for @income_type, :html => { :class => 'form-horizontal' } do |f| %>

<% if @income_type.errors.any? %>
    <ul>
    <% @income_type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

    <%= f.input :name %>
    <%= f.association :parent_income_type %>
    
    <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                income_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/income_types/delete.js.erb
$("#delete_income_type").before('<div id="flash_notice"><%= escape_javascript(flash.delete(:notice)) %></div>');
$("#income_types_count").html("<%= pluralize(@income_type.income_types.count, 'IncomeType') %>");

$("#income_types").append("<%= escape_javascript(render(:partial => @income_type)) %>");

app/views/income_types/edit.html.erb
<%- model_class = IncomeType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/income_types/index.html.erb
<div class="page-header">
  <h1><%=t "Income Types" %></h1>
</div>

<%= link_to "Create New Income Type", new_income_type_path, :class => 'btn btn-primary' %>
 <table class="table table-striped">
  <thead>
    <tr>
      <th><%= IncomeType.human_attribute_name(:name) %></th>
      <th><%= IncomeType.human_attribute_name(:parent_income_type_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @income_types.each do |income_type| %>
      <tr>
        <td><%= income_type.name %></td>
        <td><%= income_type.parent_income_type.try(:name) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_income_type_path(income_type), :class => 'btn btn-mini' %>

            <% if income_type.child_income_types.length == 0 %>
              <%= link_to 'Delete', income_type_path(income_type),
                   method: :delete, :remote => true,
                   :class => 'btn btn-mini btn-danger' %>
            <% else %>
              <%= link_to 'Delete', "javascript:void(0)", "data-original-title" => "Can't delete this while it has children!", "data-placement" => "top",
                   method: :delete,
                   :class => 'btn btn-mini btn-danger', disabled: true %>

            <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @income_types %>

app/views/income_types/new.html.erb
<%- model_class = IncomeType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>