config/routes.rb
TrackieApp::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }

  root 'dashboard#index'

     match 'versions/:id' => "versions#revert", as: :revert_version, via: [:get, :post]
resources :dashboard
resources :expense_types
  resources :income_types
    resources :incomes
      resources :expenses

    

end

app/controllers/expense_types_controller.rb
class ExpenseTypesController < ApplicationController

  def new
    @expense_type = ExpenseType.new
  end

  def create
    @expense_type = ExpenseType.new(expense_type_params)
    @expense_type.user_id = current_user.id
    if @expense_type.save
      flash[:notice] = "You have successfully created an expense type!"
      redirect_to action: 'index' 
    else
      render 'new'
    end
  end

  def index
    @expense_types = ExpenseType.page(params[:page]).per(5).order('created_at DESC')#paginate :per_page => 5, :page => params[:page]
  end

  #def show
  #end

  def edit
    expense_type
  end

  def update
    expense_type
    if @expense_type.update(expense_type_params)
      flash[:notice] = "Expense Type #{expense_type.name} was saved! #{undo_link} this!"
      redirect_to action: 'index' 
    else
      render 'edit'
    end
  end

  def destroy
    expense_type
    expense_type.destroy
    flash[:notice] = "You have successfully deleted #{expense_type.name} expense type. Press #{undo_link} to add it back!"
    redirect_to expense_types_path
  end

private

  def expense_type_params
    params.require(:expense_type).permit(:user_id, :name, :parent_expense_type_id)
  end

  def expense_type
     @expense_type ||= ExpenseType.find(params[:id])
  end

  def undo_link
    undo_link = view_context.link_to("undo", revert_version_path(@expense_type.versions.scoped.last, :method => :post))
  end

end

app/helpers/expense_types_helper.rb
module ExpenseTypesHelper
end

app/views/expense_types/_form.html.erb
<%= simple_form_for @expense_type, :html => { :class => 'form-horizontal' } do |f| %>
<% if @expense_type.errors.any? %>
    <ul>
    <% @expense_type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>
    <%= f.input :name %>
  
    <%= f.association :parent_expense_type %>
    
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                expense_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/expense_types/edit.html.erb
<%- model_class = ExpenseType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/expense_types/index.html.erb
<div class="page-header">
  <h1><%=t "Expense Types" %></h1>
</div>

<%= link_to "Create New Expense Type", new_expense_type_path, :class => 'btn btn-primary' %>
 <table class="table table-striped">
  <thead>
    <tr>
      <th><%= ExpenseType.human_attribute_name(:name) %></th>
      <th><%= ExpenseType.human_attribute_name(:parent_expense_type_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @expense_types.each do |expense_type| %>
      <tr>
        <td><%= expense_type.name %></td>
        <td><%= expense_type.parent_expense_type.try(:name) || "None" %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_expense_type_path(expense_type), :class => 'btn btn-mini' %>

            <% if expense_type.child_expense_types.length == 0 %>
              <%= link_to 'Delete', expense_type_path(expense_type),
                   method: :delete,data: { confirm: 'Press Ok to Delete the Expense Type' + ' ' + expense_type.try(:name).to_s + '?' },
                   :class => 'btn btn-mini btn-danger' %>
            <% else %>
              <%= link_to 'Delete', "javascript:void(0)", "data-original-title" => "Can't delete this while it has children!", "data-placement" => "top",
                   method: :delete,
                   :class => 'btn btn-mini btn-danger', disabled: true %>

            <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @expense_types %>

app/views/expense_types/new.html.erb
<%- model_class = ExpenseType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>